config/routes.rb
Gt2::Application.routes.draw do
  get   'login' => 'sessions#new'
  post  'logout' => 'sessions#destroy'
  post  "sessions/create"

  get   'heartbeat' => 'heartbeat#index'

  resource :password, only: [:edit, :update]
  resource :ndays, only: [:update]

  namespace :api do
    resources :events, only: [:create]
    resources :stats, only: [:index]
  end

  resources :apps do
    resource :stat, only: [:show]
  end

  resources :charts

  get 'profile' => 'users#profile'
  patch  "users/:id", as: :user, controller: :users, action: :update

  root  'users#profile'

  mount Sidekiq::Web => '/sidekiq'

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword

  has_secure_password

  validates_presence_of :email, :name
  validates_presence_of :password, :on => :create

  before_save :init_api_key

  field :name
  field :email
  field :password_digest

  field :api_key
  field :ndays, type: Integer, default: 30


  has_many :apps

  private
  def init_api_key
    self.api_key ||= SecureRandom.hex
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user

  def update
    current_user.update_attributes(permitted_params[:user])
    redirect_to profile_path, notice: I18n.t('messages.users.updated')
  end

  def profile
    @user = current_user
    @sidebar_links = {I18n.t('labels.links') => [{name: I18n.t('passwords.edit.title'), href: edit_password_path}]}
  end

  private
  def permitted_params
    params.permit(:user => [:name, :email, :password, :password_confirmation, :api_key])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_apps.html.haml
%h2= t('labels.apps')

- if current_user.apps.present?

  %table{class: 'table'}
    %tr
      %th= t('helpers.label.app.name')
      %th= t('helpers.label.app.link')
      %th= t('helpers.actions')
    - current_user.apps.each do |app|
      %tr
        %td= app.name
        %td= link_to_charts(app)
        %td
          = link_to t('labels.edit'), edit_app_path(app), class: 'btn btn-mini'
          = link_to t('labels.delete'), app_path(app), method: :delete,
            data: {confirm: 'Are you sure?'}, class: 'btn btn-mini btn-danger'
- else
  = t('labels.no_apps')

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  = f.error_notification

  = f.input :name
  = f.input :api_key, input_html: {class: 'input-xlarge'}

  #form-actions
    = f.submit nil, :class => 'btn btn-primary'

app/views/users/profile.html.haml
- content_for(:sidebar) do
  = display_sidebar(@sidebar_links)

%h1= t('labels.profile_title', username: current_user.name)

= render partial: 'form'

= render partial: 'apps'

#new_app
  = link_to t('helpers.submit.app.create'), new_app_path