config/routes.rb
Gt2::Application.routes.draw do
  get   'login' => 'sessions#new'
  post  'logout' => 'sessions#destroy'
  post  "sessions/create"

  get   'heartbeat' => 'heartbeat#index'

  resource :password, only: [:edit, :update]
  resource :ndays, only: [:update]

  namespace :api do
    resources :events, only: [:create]
    resources :stats, only: [:index]
  end

  resources :apps do
    resource :stat, only: [:show]
  end

  resources :charts

  get 'profile' => 'users#profile'
  patch  "users/:id", as: :user, controller: :users, action: :update

  root  'users#profile'

  mount Sidekiq::Web => '/sidekiq'

end

app/views/apps/_charts.html.erb
<%- model_class = Chart -%>
<%- if charts.present? %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
      </thead>
      <tbody>
      <% charts.each do |chart| %>
          <tr>
            <td><%= link_to chart.name, chart_path(chart) %></td>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_chart_path(chart), :class => 'btn btn-mini' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          chart_path(chart),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-mini btn-danger' %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
 <%- else %>
    <h4><%= t('labels.no_charts') %></h4>
 <% end %>

<%= link_to t('helpers.submit.chart.create'),
            new_chart_path(chart: {app_id: @app.id}),
            :class => 'btn btn-primary' %>

app/views/apps/_form.html.erb
<%= simple_form_for @app, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>

  <%= f.hidden_field :user_id, value: @app.user_id || current_user.id %>

  <%= f.input :name %>
  <%= f.input :id, readonly: true %>
  <%= f.input :app_key %>

  <%= render partial: 'charts', object: @app.charts %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                profile_path, :class => 'btn' %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<%- model_class = App -%>
<div class="page-header">
  <h1><%=t '.title', :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/apps/index.html.erb
<%- model_class = App -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:app_key) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= link_to app.id, app_path(app) %></td>
        <td><%= app.name %></td>
        <td><%= app.app_key %></td>
        <td><%= app.user_id %></td>
        <td><%=l app.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_app_path(app), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      app_path(app),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_app_path,
            :class => 'btn btn-primary' %>

app/views/apps/new.html.erb
<div class="page-header">
  <h1><%=t '.title' %></h1>
</div>
<%= render :partial => 'form' %>

app/views/apps/show.html.erb
<%- model_class = App -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @app.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:app_key) %>:</strong></dt>
  <dd><%= @app.app_key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @app.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_app_path(@app), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              app_path(@app),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>