config/routes.rb
Gt2::Application.routes.draw do
  get   'login' => 'sessions#new'
  post  'logout' => 'sessions#destroy'
  post  "sessions/create"

  get   'heartbeat' => 'heartbeat#index'

  resource :password, only: [:edit, :update]
  resource :ndays, only: [:update]

  namespace :api do
    resources :events, only: [:create]
    resources :stats, only: [:index]
  end

  resources :apps do
    resource :stat, only: [:show]
  end

  resources :charts

  get 'profile' => 'users#profile'
  patch  "users/:id", as: :user, controller: :users, action: :update

  root  'users#profile'

  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/api/stats_controller.rb
class Api::StatsController < Api::ApplicationController
  before_filter :verify_user_permission

  rescue_from StandardError, :with => :error_render_method

  def index
    chart = Chart.where(_id: params[:chart_id]).first

    options = {ndays: params[:ndays]}

    renderer = Gt2::ChartRenderer.new(chart.config, chart.app, options)

    render_json categories: renderer.categories,
                data: renderer.result
  end

  private
  def verify_user_permission
    chart = Chart.where(_id: params[:chart_id]).first
    user = User.where(api_key: params[:api_key]).first

    unless chart && user && chart.app.user.id == user.id
      render_error('Authentication failed', 403)
    end
  end

  def error_render_method(ex)
    logger.error("API ERROR: #{ex}")
    ex.backtrace.each{|line| logger.error(line) }

    render_error "Oops", 500
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_filter :authenticate_user

  def show
    app = App.find(params[:app_id])

    chart = if params[:chart_id]
              app.charts.to_a.find{|c| c.id.to_s == params[:chart_id]}
            else
              app.charts.first
            end

    @presenter = StatPresenter.new(chart)
  end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/_adjust_ndays.html.haml
= form_tag(ndays_path, method: :patch, class: 'form-inline', id: 'ndays_form') do
  = t('.title')

  = text_field_tag 'ndays', @presenter.ndays, class: 'string'
  = button_tag t('.submit'), type: 'submit', class: 'btn'

app/views/stats/_query_examples.html.haml
%a{class: 'btn', id: 'btn_show_examples'}= I18n.t('labels.query_examples.show')

#examples
  %h3= t('labels.query_examples.title')

  %h4= t('labels.query_examples.send_data')
  %pre
    curl -X POST #{api_events_url} -d "app_id=#{@presenter.app.id}&token=#{@presenter.app.app_key}&user_id=id1&event=#{@presenter.chart_first_event}"

  %h4= t('labels.query_examples.get_data')

  %pre
    curl "#{api_stats_url}?api_key=#{current_user.api_key}&chart_id=#{@presenter.chart.id}&ndays=30"

app/views/stats/_single_chart.html.haml
:javascript
  $(function () {
      $('##{presenter.uuid}').highcharts({
          plotOptions: {
            series: {
              animation: false
            }
          },
          credits: {
              text: '© Grafix&lt;T&gt;',
              href: 'http://tech.tulentsev.com'
          },
          title: {
              text: #{ presenter.chart_name.to_json },
              x: -20 //center
          },
          xAxis: {
              categories: #{ presenter.categories.to_json },
              tickInterval: 5
          },
          yAxis: {
              title: {
                  text: false
              },
              plotLines: [{
                  value: 0,
                  width: 1,
                  color: '#808080'
              }]
          },
          legend: {
              borderWidth: 1
          },

          tooltip: {
            pointFormat: #{ presenter.format_string.to_json },
            style: {
              fontWeight: 'bold'
            }
          },
          series: #{ presenter.chart_data.to_json }
      });
  });


%div{id: presenter.uuid}}

app/views/stats/show.html.haml
- content_for(:sidebar) do
  = display_sidebar(@presenter.sidebar_links)


= render partial: 'adjust_ndays'

- @presenter.each_chart do |chart_presenter|
  = render partial: "single_chart", locals: {presenter: chart_presenter}


= render partial: 'query_examples'