config/routes.rb
Gt2::Application.routes.draw do
  get   'login' => 'sessions#new'
  post  'logout' => 'sessions#destroy'
  post  "sessions/create"

  get   'heartbeat' => 'heartbeat#index'

  resource :password, only: [:edit, :update]
  resource :ndays, only: [:update]

  namespace :api do
    resources :events, only: [:create]
    resources :stats, only: [:index]
  end

  resources :apps do
    resource :stat, only: [:show]
  end

  resources :charts

  get 'profile' => 'users#profile'
  patch  "users/:id", as: :user, controller: :users, action: :update

  root  'users#profile'

  mount Sidekiq::Web => '/sidekiq'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Grafix<T>" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'Grafix<T>', profile_path, class: 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
              <!--<li><%= link_to "Link1", "/path1"  %></li>-->
              <!--<li><%= link_to "Link2", "/path2"  %></li>-->
              <li><%= link_to t('helpers.links.logout'), "/logout", method: :post if current_user  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>

          <% if content_for?(:sidebar) %>
            <%= yield(:sidebar) %>
          <% end %>
        </div><!--/row-->

      <footer>
        <hr/>
        <p>&copy; Tulentsev Software Shop 2013, commit SHA-1: <%= git_version %></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>